/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VoteCoin__factory } from "./VoteCoin__factory";
export { VoteERC20__factory } from "./VoteERC20__factory";
